### ISSUE TITLE
label not available i guess

### ISSUE THREAD

**Issue by vivek14632** [vivek14632/LungCancerProject#16]
Reading label for 7b76426f64cb4fbe3d4caa1dcbf47a2f
Reading label for 49c88f7cc77341c9ae4e64243f9912fc
Traceback (most recent call last):
  File "y_matrix_generator.py", line 62, in <module>
    main()
  File "y_matrix_generator.py", line 55, in main
    np_matrix = matrix_generator(filepath)
  File "y_matrix_generator.py", line 31, in matrix_generator
    labels.append(get_label(file_name)*num)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by vivek14632** [comment]
@Rhomi can you check whether we have label for '49c88f7cc77341c9ae4e64243f9912fc'? else we need to remove that from our npy list.

**Comment by vivek14632** [comment]
@Rhomi  what the the location of CSV file which you got from Kaggle which has more labels including solution for stage 1.?

**Comment by vivek14632** [comment]
ee71210fa398cbb080f6c537a503e806.npy contains (152, 512, 512) images
Reading images from e56b9f25a47a42f4ae4085005c46109c.npy
e56b9f25a47a42f4ae4085005c46109c.npy contains (163, 512, 512) images
Reading images from 1183f213c1c821df18aad63890920403.npy
1183f213c1c821df18aad63890920403.npy contains (162, 512, 512) images
Reading images from 2143d78ca33eb69f667edd80ddbff6de.npy
2143d78ca33eb69f667edd80ddbff6de.npy contains (255, 512, 512) images
Reading images from 7692b05abf70dbac5292e91918e98913.npy
7692b05abf70dbac5292e91918e98913.npy contains (176, 512, 512) images

**Comment by Rhomi** [comment]
Missing file image (npy) file 0b20184e0cd497028bdd155d9fb42dc9 given a label 2.

**Comment by vivek14632** [comment]
[vivek4@itn3 vivek]$ python y_matrix_generator.py /work/v/vivek4/stage1_clean_bak /work/v/vivek4/stage1_clean_bak_Y_matrix
Traceback (most recent call last):
  File "y_matrix_generator.py", line 62, in <module>
    main()
  File "y_matrix_generator.py", line 53, in main
    print("Reading files from {}".format(filepath))
ValueError: zero length field name in format
[vivek4@itn3 vivek]$ python y_matrix_generator.py /work/v/vivek4/stage1_clean_bak /work/v/vivek4/stage1_clean_bak_Y_matrix
Traceback (most recent call last):
  File "y_matrix_generator.py", line 62, in <module>
    main()
  File "y_matrix_generator.py", line 53, in main
    print("Reading files from {}".format(filepath))
ValueError: zero length field name in format

**Comment by vivek14632** [comment]
[vivek4@itn3 vivek]$ python y_matrix_generator.py /work/v/vivek4/stage1_clean_bak /work/v/vivek4/stage1_clean_bak_Y_matrix
Traceback (most recent call last):
  File "y_matrix_generator.py", line 62, in <module>
    main()
  File "y_matrix_generator.py", line 53, in main
    print("Reading files from {}".format(filepath))
ValueError: zero length field name in format

**Comment by vivek14632** [comment]
python y_matrix_generator.py /work/v/vivek4/stage1_clean_bak /work/v/vivek4/stage1_clean_bak_Y_matrix

**Comment by Rhomi** [comment]
Command line - how it works for now

python y_matrix_generator.py D:\Learning\Cancer_Project\Data\sample_images_clean D:\Docs D:\Learning\Cancer_Project\Data\stage1_labels.csv

**Comment by vivek14632** [comment]
(Pdb) filepath
'/work/v/vivek4/stage1_clean_bak'
(Pdb) print("Reading files from {}".format(filepath))
*** ValueError: zero length field name in format
(Pdb) print("Reading files from {0}".format(filepath))
Reading files from /work/v/vivek4/stage1_clean_bak

**Comment by vivek14632** [comment]
https://stackoverflow.com/questions/21034954/valueerror-zero-length-field-name-in-format-in-python2-6-6

**Comment by vivek14632** [comment]
Reading label for 49c88f7cc77341c9ae4e64243f9912fc
